apiVersion: v1
kind: Service
metadata:
  name: deployment-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: myapp3
  ports:
  - port: 80
    name: http
    targetPort: 80
