apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  strategy: 
     type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql 
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                 secretKeyRef:
                   name: mysecret
                   key: db-password
          resources:
             limits:
               memory: "128Mi"
               cpu: "500m"
          ports:
          - containerPort: 3306
          volumeMounts:
             - name: mysql-persistent-storage
               mountPath: /var/lib/mysql
             - name: usermanaged-configmap-db-script
               mountPath: /docker-entrypoint.initdb.d
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
             claimName: azure-managed-disk-pvc
        - name: usermanaged-configmap-db-script     
          configMap: 
             name: usermanaged-configmap-db-script