apiVersion: apps/v1
kind: ReplicaSet
metadata: 
   name: myapp2-rs
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: myapp2
  template:
    metadata:  #Dictionary
      name: myapp2-pod
      labels:
        app: myapp2   # Key-Value Pairs
    spec:
      containers:  #list
      - name: myapp2
        image: stacksimplify/kubenginx:2.0.0
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 80         