## This Storage is used for Custom Volume Claim Purposes,If you need only customized volume storages
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
parameters:
  storageAccountType: Premium_LRS
  kind: managed 
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
